[behavior]
scrolling = "center"
file_action = "true"

# hex rgb
[color]
background = "000000"
foreground = "FFFFFF"

[debug]
enabled = true
padding_bot = 1
padding_top = 3
spacing_bot = 4
spacing_top = 1

[setup]
working_dir = "."
