[behavior]
file_action = "true"
path_node_sort = "dirs_top_simple" # enum: none, dirs_top_simple, dirs_bot_simple
scrolling = "center" # enum: center, editor

# hex rgb
[color]
background = "000000"
foreground = "FFFFFF"

[composition]
indent = 2
show_indent = false
use_utf8 = true

[debug]
enabled = false
padding_bot = 3
padding_top = 3
spacing_bot = 0
spacing_top = 1

[setup]
working_dir = "."
