[behavior]
scrolling = "center"
file_action = "true"

# hex rgb
[color]
background = "000000"
foreground = "FFFFFF"

[debug]
enabled = false
padding_bot = 3
padding_top = 3
spacing_bot = 0
spacing_top = 1

[setup]
working_dir = "."
