[package]
authors = ["Dirk Kretschmann <kretschmanndi@gmail.com>"]
edition = "2018"
license = "MIT"
name = "twilight-commander"
version = "0.6.0"

[dependencies]
ncurses = "5.99.0"
toml = "0.5.3"
serde = { version = "1.0.101",  features = ["derive"] }
