[package]
authors = ["Dirk Kretschmann <kretschmanndi@gmail.com>"]
edition = "2018"
license = "MIT"
name = "twilight-commander"
version = "0.7.0"

[dependencies]
termion = "1.5.3"
toml = "0.5.3"
serde = { version = "1.0.101",  features = ["derive"] }
